version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: techmate-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin1
      MYSQL_DATABASE: techmate_inventory
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: techmate:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/techmate_inventory
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin1
    ports:
      - "8081:8080"
    volumes:
      - ./uploaded-images:/app/uploaded-images

volumes:
  db_data: