INSERT INTO role (nombre) VALUES ('ADMINISTRADOR') ON DUPLICATE KEY UPDATE nombre=nombre;
INSERT INTO role (nombre) VALUES ('DIVISION') ON DUPLICATE KEY UPDATE nombre=nombre;
INSERT INTO role (nombre) VALUES ('ESTUDIANTE') ON DUPLICATE KEY UPDATE nombre=nombre;
